ERROR - 2023-09-28 05:25:08 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'sesin_a' in C:\xampp\htdocs\Primer_Proyecto\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Primer_Proyecto\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'sesin_a', 3306, '', 0)
#1 C:\xampp\htdocs\Primer_Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Primer_Proyecto\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Primer_Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Primer_Proyecto\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Primer_Proyecto\system\Validation\Validation.php(278): CodeIgniter\Validation\StrictRules\Rules->is_unique('sesinho32@gmail...', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\Primer_Proyecto\system\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('email', 'email', 'sesinho32@gmail...', Array, Array)
#7 C:\xampp\htdocs\Primer_Proyecto\system\Controller.php(141): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\Primer_Proyecto\app\Controllers\usuario_controller.php(29): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\Primer_Proyecto\system\CodeIgniter.php(932): App\Controllers\usuario_controller->formValidation()
#10 C:\xampp\htdocs\Primer_Proyecto\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\usuario_controller))
#11 C:\xampp\htdocs\Primer_Proyecto\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Primer_Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'sesin_a' in C:\xampp\htdocs\Primer_Proyecto\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Primer_Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Primer_Proyecto\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Primer_Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Primer_Proyecto\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Primer_Proyecto\system\Validation\Validation.php(278): CodeIgniter\Validation\StrictRules\Rules->is_unique('sesinho32@gmail...', 'email', Array, NULL, 'email')
#5 C:\xampp\htdocs\Primer_Proyecto\system\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('email', 'email', 'sesinho32@gmail...', Array, Array)
#6 C:\xampp\htdocs\Primer_Proyecto\system\Controller.php(141): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\Primer_Proyecto\app\Controllers\usuario_controller.php(29): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\Primer_Proyecto\system\CodeIgniter.php(932): App\Controllers\usuario_controller->formValidation()
#9 C:\xampp\htdocs\Primer_Proyecto\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\usuario_controller))
#10 C:\xampp\htdocs\Primer_Proyecto\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Primer_Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-09-28 05:25:08 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'sesin_a'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `usuarios`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(278): CodeIgniter\Validation\StrictRules\Rules->is_unique('sesinho32@gmail.com', 'email', [...], null, 'email')
 5 SYSTEMPATH\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('email', 'email', 'sesinho32@gmail.com', [...], [...])
 6 SYSTEMPATH\Controller.php(141): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\usuario_controller.php(29): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\usuario_controller->formValidation()
 9 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\usuario_controller))
10 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-28 21:10:27 --> Call to undefined function App\Controllers\redrect()
in APPPATH\Controllers\login_controller.php on line 59.
 1 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\login_controller->auth()
 2 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login_controller))
 3 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-28 22:07:16 --> Call to undefined function App\Controllers\redrect()
in APPPATH\Controllers\login_controller.php on line 59.
 1 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\login_controller->auth()
 2 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login_controller))
 3 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
